[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:laravel-scheduler]
command=php /var/www/html/artisan schedule:run --no-interaction
autostart=true
autorestart=true
startretries=999